### ISSUE TITLE
Instance marked DOWN despite being UP

### ISSUE THREAD

**Issue by tscs37** [TheKinrar/mastodon-instances#81] opened 2019-04-18 15:51 UTC
My instance, `pony.social` is being marked as DOWN with ETIMEDOUT, the instance is however perfectly fine and online. I also checked if my firewall flagged any hosts to block but there doesn't seem to be anything of note happening.

There doesn't seem to be any reason for it being marked DOWN...

**Comment by TheKinrar** [comment] 2019-11-27 16:00
Duplicate of #72

**Closed by TheKinrar** 2019-11-27 16:00 UTC

**Comment by shebang79** [comment] 2020-01-19 02:49
I'm having this issue on freespeech.host, it doesn't even show up in the instances list anymore.
